### ISSUE TITLE
need a readme

### ISSUE THREAD

**Issue by huangming** [horosgrisa/mysql-colorize#1]
I am new to linux.
looking your repositories https://github.com/randsonjs/myterm-color,
I don't know how to install GRC in centos.
Could you tell me how to?
I am using oh-my-zsh now.

**Comment by horosgrisa** [comment]
Hi
I don't use centos, but maybe you can install grc with `[sudo] yum install grc`
If this does not work, read [INSTALL](https://github.com/garabik/grc/blob/master/INSTALL)
But if you would like to use my plugin for mysql, you dont need install grc, because it use own incorporated grc.
